version: 2.1

executors:
  docker-build-buster:
    docker:
      - image: circleci/buildpack-deps:buster

jobs:
  build:
    executor: docker-build-buster
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: make docker-build
      - run:
          name: Save Docker image
          command: DOCKER_IMAGE_FILENAME=image.tar make docker-save
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test:
    executor: docker-build-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Test Docker image
          command: make docker-test
  publish-dockerhub:
    executor: docker-build-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Docker Hub
          command: make dockerhub-push
  publish-quay:
    executor: docker-build-buster
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: DOCKER_IMAGE_FILENAME=/tmp/workspace/image.tar make docker-load
      - run:
          name: Push Docker image to Quay.io
          command: make quay-push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish-dockerhub:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - publish-quay:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
