version: 2.1

executors:
  docker-build-jammy:
    docker:
      - image: cimg/base:current-22.04

jobs:
  build-and-publish:
    executor: docker-build-jammy
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Create a new builder instance
          command: docker buildx create --use
      - run:
          name: Build and publish
          command: make container-buildx-push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-publish:
          context:
            - quay-nn
            - github-registry
          filters:
            tags:
              only: /.*/
